ansible_python_interpreter: /usr/bin/python3
fa1_ip: 10.224.113.210
fa1_token: b797c313-a84f-b5fe-2d41-2e5256c79c24
fa2_ip: 10.224.113.211
fa2_token: 610a1e56-54a3-1227-4d98-45e27652eb34
demo_vol: ansible-src
demo_pod: demo-pod
fa1_iscsi_port: ct0.eth1
fa2_iscsi_port: ct0.eth1
src_mount_path: /mnt/ansible-src
tgt_mount_path: /mnt/ansible-tgt
orig_volume: linux-lun-01
tgt_vol: ansible-tgt
pod_vol: demo-pod::ansible-src

